### ISSUE TITLE
milstd library outdated and not maintained

### ISSUE THREAD

**Issue by z3r03nna** [jetelain/Arma3TacMap#29]
Hi,

you are using this library: https://github.com/spatialillusions/milstd

There is a Note:
"You should migrate to using the following two repositories instead:

    https://github.com/spatialillusions/mil-std-2525

    https://github.com/spatialillusions/stanag-app6
"

I believe there are errors (for example the airmobile / air assault marker is wrong) and they may be fixed in up2date libraries.

**Comment by jetelain** [comment]
Hi,

In fact I've forget an initialization call `ms.setStandard("APP6");` that leads to some errors.

**Comment by jetelain** [comment]
Hi,

It's fixed, it affected all symbols from MIL-STD-2525(D)

Site :
![image](https://github.com/jetelain/Arma3TacMap/assets/33651126/76070165-b4a9-4ef9-94c7-3aa4aba0c055)

Standard :
![image](https://github.com/jetelain/Arma3TacMap/assets/33651126/40b3a027-04dc-45ab-8813-25c981ab0e07)
