### ISSUE TITLE
[Feature request] Show indicator if created marker is Metis marker compatible

### ISSUE THREAD

**Issue by MildlyInterested** [jetelain/Arma3TacMap#30]
1. Create map with markers in TacMap
2. Use map in Arma
3. Notice some markers will be generic because metis marker doesn't have the corresponding icon

Knowing in advance which markers won't show "properly" in game would allow planners to change icon or add Additional Information to the marker to make it more clear.
Below is a picture how that could look in the web interface.
![image](https://github.com/jetelain/Arma3TacMap/assets/57712666/6507d5ce-e9cd-4090-9937-be003f08e20f)
A whole preview like pictured might be to much work so a simple text/warning on incompatible icons would be enough.

**Comment by jetelain** [comment]
Hi,
Good idea, and that should not be really complex. I will have a look this weekend.
I was also planning to create a port of "milsymbol" to Arma 3 within cTab+ a get full "perfect" export. It's the hidden goal behind https://github.com/jetelain/milsymbolsharp (mass generate symbols for Arma 3).

**Comment by jetelain** [comment]
Hi, it's available

![image](https://github.com/jetelain/Arma3TacMap/assets/33651126/f73d5c1c-810e-4f46-9ea3-ed9deccf6746)
