### ISSUE TITLE
Export markers to Arma 3 choose channel

### ISSUE THREAD

**Issue by MildlyInterested** [jetelain/Arma3TacMap#34]
Currently the provided code snippet
![image](https://github.com/jetelain/Arma3TacMap/assets/57712666/78d629f0-48eb-4b9a-9676-ab7bcb36e2fb)
will create the markers in the global channel by default, being able to change that would be nice.
Possible settings: Global,Side,customID

**Comment by jetelain** [comment]
Hi,
I've added an option in the "Layers export" below the regular export to choose the target channel.
Metis markers does not support custom channels, so the available options are : Global, Side, Group, Command and Vehicle

**Comment by LucyferHW** [comment]
Hey, is this feature functional?
I can not find it in my export menu.

**Comment by jetelain** [comment]
Hi, yes it's functional : you have to scroll down to "Export Layers to Arma3"

![image](https://github.com/user-attachments/assets/faeef625-42fe-441a-9e4a-86b904deaf06)

**Comment by LucyferHW** [comment]
Thank you very much for super fast response.

I am doing this steps (see Screenshots) and sadly can not find it.
![image](https://github.com/user-attachments/assets/98a10ca0-5752-4edc-b69a-4bcfdca66e98)
![image](https://github.com/user-attachments/assets/e63bd62b-3421-4ffa-9a44-29b1a75c0f76)
![image](https://github.com/user-attachments/assets/c6138742-80b6-43a7-9aeb-99d21cb90ee0)

**Comment by jetelain** [comment]
Hi,
In fact it appears only if you have more than one layer. It's not intentional.
As a workaround you can add an empty layer to unlock access to the feature.

https://github.com/jetelain/Arma3TacMap/blob/8f82513fa5584b4a9720d9fb1a5f9c15f90b8142/Arma3TacMapWebApp/Views/TacMaps/Export.cshtml#L46C1-L46C36

**Comment by LucyferHW** [comment]
Big Thank you for the help!
It is working now for me too. :)
Sorry for the trouble.
