### ISSUE TITLE
Inability to edit map/see markers being currently edited

### ISSUE THREAD

**Issue by 61stMechanizedArma** [jetelain/Arma3TacMap#40]
I have a current map that I have spent a substantial amount of time on as well as using it for my community, for some reason when I use the link that goes with the map it shows the name of the map but none of the markers are their and it takes almost 10 minutes to load I cannot sign in either because it gets stuck on the sign in page. I tried to narrow it down to being just an issue with me but I have had around 12 people check and they are having the same issue.

**Comment by jetelain** [comment]
Hi, server had performance issues. It's resolved
